<?php
declare(strict_types=1);

// WeatherForecast SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

WeatherForecastUtility::setRegistrar(function (WeatherForecastUtility $u): void {
    $u->clean = [WeatherForecastClean::class, 'call'];
    $u->done = [WeatherForecastDone::class, 'call'];
    $u->make_error = [WeatherForecastMakeError::class, 'call'];
    $u->feature_add = [WeatherForecastFeatureAdd::class, 'call'];
    $u->feature_hook = [WeatherForecastFeatureHook::class, 'call'];
    $u->feature_init = [WeatherForecastFeatureInit::class, 'call'];
    $u->fetcher = [WeatherForecastFetcher::class, 'call'];
    $u->make_fetch_def = [WeatherForecastMakeFetchDef::class, 'call'];
    $u->make_context = [WeatherForecastMakeContext::class, 'call'];
    $u->make_options = [WeatherForecastMakeOptions::class, 'call'];
    $u->make_request = [WeatherForecastMakeRequest::class, 'call'];
    $u->make_response = [WeatherForecastMakeResponse::class, 'call'];
    $u->make_result = [WeatherForecastMakeResult::class, 'call'];
    $u->make_point = [WeatherForecastMakePoint::class, 'call'];
    $u->make_spec = [WeatherForecastMakeSpec::class, 'call'];
    $u->make_url = [WeatherForecastMakeUrl::class, 'call'];
    $u->param = [WeatherForecastParam::class, 'call'];
    $u->prepare_auth = [WeatherForecastPrepareAuth::class, 'call'];
    $u->prepare_body = [WeatherForecastPrepareBody::class, 'call'];
    $u->prepare_headers = [WeatherForecastPrepareHeaders::class, 'call'];
    $u->prepare_method = [WeatherForecastPrepareMethod::class, 'call'];
    $u->prepare_params = [WeatherForecastPrepareParams::class, 'call'];
    $u->prepare_path = [WeatherForecastPreparePath::class, 'call'];
    $u->prepare_query = [WeatherForecastPrepareQuery::class, 'call'];
    $u->graphql_body = [WeatherForecastGraphql::class, 'body'];
    $u->graphql_errors = [WeatherForecastGraphql::class, 'errors'];
    $u->result_basic = [WeatherForecastResultBasic::class, 'call'];
    $u->result_body = [WeatherForecastResultBody::class, 'call'];
    $u->result_headers = [WeatherForecastResultHeaders::class, 'call'];
    $u->transform_request = [WeatherForecastTransformRequest::class, 'call'];
    $u->transform_response = [WeatherForecastTransformResponse::class, 'call'];
});
